### ISSUE TITLE
Error - This game version is too low for Build Settings (SFS 1.5.9.8, BuildSettings 2.1.4)

### ISSUE THREAD

**Issue by Earth-And-Moon** [Neptune-Sky/SFSBuildSettings#1]
I just installed BuildSettings 2.1.4 on SFS 1.5.9.8, but it does not work.
I pressed F12 in the game to open the console and this are the errors:

![Screenshot of error stack](https://i.imgur.com/pRPiJqJ.png)

Which is the latest version of BuildSettings that is supported by SFS 1.5.9.8?

**Comment by Neptune-Sky** [comment]
Won't fix. This mod does not support old versions of the game. Update your game or use an old version of the mod.

**Comment by Earth-And-Moon** [comment]
Yes, but which version of BuildSettings do I need? I'm too lazy to test every single version of BuildSettings ...
Or write the minimum SFS version to the releases in the releases section.

**Comment by Neptune-Sky** [comment]
Just update your game and this won't be an issue... I fail to see any reason someone would want to completely avoid opening steam to make sure sfs doesn't get updated. 

As I stated, I do not support old versions and it is up to the user to find the version that works for them if they decide to do something 99.999% of people don't do. If you're always on the latest version of the game using the latest version of the mod you will never have to do this.
